### ISSUE TITLE
Images missing and file names with spaces.

### ISSUE THREAD

**Issue by el-guero-mero** [amitsaoji/Cats-HTML-Email#1]
Hello Amit,

The images are missing when I download the project. Also, there are spaces in the file names which won't work without our environment here (Apple's internal environment doesn't allow for spaces in file names). Can you please address? Many thanks, Mateo

**Comment by amitsaoji** [comment]
Hello Mateo,

Thank you for bringing this to my attention, I’ve just updated the code on GitHub.

Please let me know if there are any further issues.

Best Regards,
Amit Saoji

**Comment by el-guero-mero** [comment]
Wonderful, thank you Amit :)
